<?php

namespace app\school\controller;


use cmf\controller\SchoolBaseController;
use think\Db;

class SurveyController extends  SchoolBaseController{




    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('cur','survey');
    }



    public function index(){
        $param = $this->request->param();
        $school_id = session('school.id');
        $Ok_inform_id = array_column(Db::name('class_survey_user')->where(['school_id'=>$school_id])->select()->toArray(),'survey_id');
        $where = [
            ['types','<>',1],
            ['school_show','=',1]
        ];
        $whereOr = [
            ['school_id','like',"%{$school_id}%"],
            ['school_id','=',"[]"],
            ['school_id','=',null],
            ['push_school_id','=',$school_id]
        ];
        $status = $param['status'] ?? '';
        if($status == 1){
            $where[] = ['id','IN',$Ok_inform_id];
        }elseif($status == 2){
            $where[] = ['id','not IN',$Ok_inform_id];
        }
        $keyword = $param['keyword'] ?? 0;
        if($keyword){
            $where[] = ['title' , 'like' , "%{$keyword}%"];
        }
        $type = $param['type'] ?? 0;
        if($type){
            $where[] = ['types' , '=' , $type];
        }
        $list = Db::name('class_survey')->where($where)->where(function ($query) use ($whereOr){
            $query->whereOr($whereOr);
        })->order('id desc')->paginate(20);
        $list->each(function ($v,$k){
            $v['addtime'] =  date('Y-m-d H:i:s',$v['addtime']);
            $v['end_time'] =  date('Y-m-d H:i:s',$v['end_time']);
            return $v;
        });
        $this->assign('list',$list);
        $this->assign('Ok_inform_id',$Ok_inform_id);
        $this->assign('page',$list->render());
        return $this->fetch();
    }

    public function content(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where(['id'=>$id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        $info['content'] = json_decode($info['content'],true);
        $school_id = session('school.id');
        $data= Db::name('class_survey_user')->where(['survey_id'=>$id,'school_id'=>$school_id])->find();
        $answer = json_decode($data['answer'],true);
        $this->assign('answer',$answer);
        $this->assign('status',$data ? 1 : 0);
        $this->assign('select_list',['A','B','C','D','E','F','G','H','I','J','K','L','M','N']);
        if($info['push_school_id'] == $school_id){
            $school_id = session('school.id');
            $school_grade_key = Db::name('school_grade')->field('content')->where('school_id',$school_id)->find()['content'] ?? '[]';
            $school_grade_key = json_decode($school_grade_key,true);
            $key = [];
            foreach ($school_grade_key as $k=>$v){
                $key = array_merge($key,$v);
            }
            $content = [];
            foreach ($this->configs as $k=>$v){
                if(in_array($k,$key)){
                    $v['key'] = $k;
                    $content[] = $v;
                }
            }
            $this->assign('content',$content);
            $info['keys'] = json_decode($info['keys'],true);
        }
        $this->assign('info',$info);
        return $this->fetch();
    }

    public function detail(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where('types',2)->where(['id'=>$id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        $info['end_time'] = date('Y-m-d H:i:s',$info['end_time']);
        $content = json_decode($info['content'],true);
        $info['content'] = $content;
        $count = 0;
        $school_id = json_decode($info['school_id'],true);
        if($info['school_show']){
            $count += count($school_id);
        }
        if($info['teacher_show']){
            $where = [];
            if($school_id){
                $where['school_id'] = $school_id;
            }
            $count += Db::name('class_teacher')->where($where)->group('uid')->count();
        }
        if($info['patriarch_show']){
            $where = [];
            if($school_id){
                $where['school_id'] = $school_id;
            }
            $patriarch_info = Db::name('class_patriarch')->where($where)->order('id desc')->select();
            $survey_user_info= Db::name('class_survey_user')->where(['survey_id'=>$id])->select();
            $patriarch_id = array_column($survey_user_info->toArray(),'patriarch_id');
            $read_count = $unread_count = 0;
            foreach ($patriarch_info as $k=>$v){
                if(in_array($v['id'],$patriarch_id)){
                    $read_count += 1;
                }else{
                    $unread_count += 1;
                }
            }
            $count += $read_count;
            $count += $unread_count;
        }

        foreach ($content as $k=>$v){
            $detail = $v['detail'];
            $info_val= $v['info'] ?? '';
            if($v['type'] ==1 || $v['type'] ==2){
                foreach ($info_val as $key=>$item){
                    $ratio = $detail[$key] ?  ($detail[$key] / $count) * 100 : 0;
                    $info_val[$key] = [
                        'option' => $item,
                        'count' => $detail[$key] ?? 0,
                        'ratio' =>$ratio > 100 ? 100 : (int)$ratio
                    ];
                }
            }else{
                $ratio = $detail[0] ? ($detail[0] / $count) * 100 : 0;
                $info_val = [
                    'count' => $detail[0] ?? 0,
                    'ratio' =>  $ratio > 100 ? 100 : (int)$ratio
                ];
            }
            unset($v['detail']);
            $v['info'] = $info_val;
            $content[$k] = $v;
        }

        $info['content'] = $content;
        $info['school_id'] = json_decode($info['school_id'],true);
        $school_info = Db::name('school')->select();
        $this->assign('select_list',['A','B','C','D','E','F','G','H','I','J','K','L','M','N']);
        $this->assign('school_info',$school_info);
        $this->assign('info',$info);
        return $this->fetch();
    }

    public function addDetail(){
        $param = $this->request->param();
        $survey_id = $param['survey_id'] ?? '';
        $answer = $param['answer'] ?? [];
        $start_time = $param['start_time'] ?? '';
        $minute = $param['minute'] ?? '';
        if(!$survey_id || !$start_time || !$minute){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where(['id'=>$survey_id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        if($info['end_time'] < time()){
            $this->error('问卷已过期');
        }
        $school_id = session('school.id');
        $exist = Db::name('class_survey_user')->where(['survey_id'=>$survey_id,'school_id'=>$school_id])->find();
        if($exist){
            $this->error('此问卷您已做完');
        }
        $content = json_decode($info['content'],true);
        $count = count($content);
        foreach ($content as $k=>$v){
            $answer_key =isset($answer[$k]) ? array_keys($answer[$k])[0] : $v['type'];
            $answer_value = isset($answer[$k]) ? array_values($answer[$k])[0] : ($answer_key == 3 ? '' : []);
            if(!isset($answer[$k])){
                $answer[$k] = [$answer_key=>$answer_value];
            }
            if(!$answer_key){
                $this->error('信息有误');
            }
            if(!in_array($answer_key,[1,2,3])){
                $this->error('信息有误');
            }
            if($v['type'] != $answer_key){
                $this->error('信息有误');
            }
            if($answer_key == 1){
                if(count($answer_value) > 1){
                    $this->error('单选题只能选择一个');
                }
            }
            $detail = $v['detail'];
            if($v['type'] == 1 || $v['type'] == 2){
                foreach ($answer_value as $key=>$item){
                    $detail[$item] += 1;
                }
            }else{
                if($answer_value){
                    $detail[0] += 1;
                }
            }

            $v['detail'] = $detail;
            $content[$k] = $v;
        }

        $minute = ($minute >= 60) ? ($minute / 60) : 1;
        Db::name('class_survey')->where(['id'=>$info['id']])->update(['content'=>json_encode($content,true),'count'=>$info['count'] + 1]);
        $insert = [
            'survey_id' => $info['id'],
            'uid' => 0,
            'answer' => json_encode($answer,true),
            'addtime' => time(),
            'minute' => $minute,
            'start_time' => $start_time,
            'count' => $count,
            'school_id' =>$school_id,
        ];
        Db::name('class_survey_user')->insert($insert);
        $this->success('成功');
    }





    public function add(){
        $school_id = session('school.id');
        $school_grade_key = Db::name('school_grade')->field('content')->where('school_id',$school_id)->find()['content'] ?? '[]';
        $school_grade_key = json_decode($school_grade_key,true);
        $key = [];
        foreach ($school_grade_key as $k=>$v){
            $key = array_merge($key,$v);
        }
        $content = [];
        foreach ($this->configs as $k=>$v){
            if(in_array($k,$key)){
                $v['key'] = $k;
                $content[] = $v;
            }
        }
        $this->assign('content',$content);
        return $this->fetch();
    }


    public function addpost(){
        $param = $this->request->param();
        $title = $param['title'] ?? 0;
        $content = $param['content'] ?? 0;
        $end_time = $param['end_time'] ?? 0;
        $keys = $param['key'] ?? [];
        $people_type = $param['people_type'] ?? 0;
        if(!$title){
            $this->error('请填写标题');
        }
        if(!$content){
            $this->error('请填写内容');
        }

        if(!$end_time){
            $this->error('请选择截止时间');
        }
        if(!$people_type){
            $this->error('请选择接收人员');
        }

        foreach ($content as $k=>$v){
            foreach ($v as $key=>$item){
                $value=[
                    'type' => $key,
                    'title' => $item['title'] ?? ''
                ];
                if($key != 3){
                    $value['info'] = $item['option'] ?? [];
                }
            }
            $type = $value['type'] ?? '';
            if(!in_array($type,[1,2,3])){
                $this->error('数据异常');
            }
            $content[$k] = $value;
        }
        foreach ($content as $k=>$v){
            if(!$v['title']){
                $this->error('请填写题目');
            }
            if($v['type'] == 1 || $v['type'] == 2){
                if(!is_array($v['info'])){
                    $this->error('信息有误');
                }
                if(!count($v['info'])){
                    $this->error('请添加选项');
                }
                $info = $v['info'];
                $detail = [];
                foreach ($info as $key=>$item){
                    $detail[$key] = 0;
                }
            }elseif($v['type'] == 3){
                $detail = [0];
            }else{
                $this->error('信息有误');
            }
            if($v['type'] == 2){
                if(count($v['info']) < 2){
                    $this->error('多选项至少添加两项选择');
                }
            }

            $v['detail'] = $detail;
            $content[$k] = $v;
        }
        $school_id = session('school.id');
        $end_time =strtotime($end_time);
        $insert = [
            'class_id' => 0,
            'uid' => 0,
            'title'=>$title,
            'type' => 1,
            'end_time' => $end_time,
            'content' => json_encode($content,true),
            'patriarch_id' => json_encode([] ,true),
            'addtime' => time(),
            'patriarch_show' => 0,
            'teacher_show' => 0 ,
            'keys'=>json_encode($keys,true),
            'types' => 2,
            'push_school_id' =>$school_id,
            'school_show' => 1
        ];
        $http_url = getConfigPri()['http_url'].'/Push/eliminate';
        Db::startTrans();
        try{
            $where_ = ['school_id'=>$school_id];
            if($keys){
                $where_['key'] = $keys;
            }

            if($key){
                $class_id = Db::name('class_grade_system')->alias('A')
                    ->join('class B','A.id = B.pid')
                    ->where(['A.school_id'=>$school_id,'B.key'=>$key])->column('B.id');
            }else{
                $class_id = Db::name('class_grade_system')->alias('A')
                    ->join('class B','A.id = B.pid')
                    ->where(['A.school_id'=>$school_id])->column('B.id');
            }
            foreach ($people_type as $k=>$v){
                if($v == 1){
                    $insert['patriarch_show'] = 1;
                }elseif($v == 2){
                    $insert['teacher_show'] = 1;
                }else{
                    $insert['school_show'] = 1;
                }
            }
            $survey_id = Db::name('class_survey')->insertGetId($insert);
            $where = [
                'class_id' => $class_id
            ];
            Db::name('class_patriarch')->where($where)->setInc('survey_count', 1);
            Db::name('class_teacher')->where($where)->setInc('survey_count', 1);
            Db::commit();
        }catch (\Exception $e){
            Db::rollback();
            $this->error($e->getMessage());
        }

        foreach ($people_type as $k=>$v){
            if($v == 1){
                $param_post = [
                    'field'=>'clearSurvey',
                    'type' => '1',
                    'patriarch_id' => json_encode(Db::name('class_patriarch')->where($where_)->column('id')),
                    'survey_id' => $survey_id
                ];
                curl_post($http_url,$param_post);
            }elseif($v == 2){
                $param_post = [
                    'uid' => json_encode(Db::name('class_teacher')->where($where_)->column('uid')),
                    'field'=>'clearSurvey',
                    'type' => '2',
                    'survey_id' => $survey_id
                ];
                curl_post($http_url,$param_post);
            }
        }


        $this->success('成功');
    }

    public function export(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where('types',2)->where(['id'=>$id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        $info['end_time'] = date('Y-m-d H:i:s',$info['end_time']);
        $content = json_decode($info['content'],true);
        $info['content'] = $content;
        $count = 0;
        $school_id = json_decode($info['school_id'],true);
        if($info['school_show']){
            $count += count($school_id);
        }
        if($info['teacher_show']){
            $where = [];
            if($school_id){
                $where['school_id'] = $school_id;
            }
            $count += Db::name('class_teacher')->where($where)->group('uid')->count();
        }
        if($info['patriarch_show']){
            $where = [];
            if($school_id){
                $where['school_id'] = $school_id;
            }
            $patriarch_info = Db::name('class_patriarch')->where($where)->order('id desc')->select();
            $survey_user_info= Db::name('class_survey_user')->where(['survey_id'=>$id])->select();
            $patriarch_id = array_column($survey_user_info->toArray(),'patriarch_id');
            $read_count = $unread_count = 0;
            foreach ($patriarch_info as $k=>$v){
                if(in_array($v['id'],$patriarch_id)){
                    $read_count += 1;
                }else{
                    $unread_count += 1;
                }
            }
            $count += $read_count;
            $count += $unread_count;
        }

        foreach ($content as $k=>$v){
            $detail = $v['detail'];
            $info_val= $v['info'] ?? '';
            if($v['type'] ==1 || $v['type'] ==2){
                foreach ($info_val as $key=>$item){
                    $ratio = $detail[$key] ?  ($detail[$key] / $count) * 100 : 0;
                    $info_val[$key] = [
                        'option' => $item,
                        'count' => $detail[$key] ?? 0,
                        'ratio' =>$ratio > 100 ? 100 : (int)$ratio
                    ];
                }
            }else{
                $ratio = $detail[0] ? ($detail[0] / $count) * 100 : 0;
                $info_val = [
                    'count' => $detail[0] ?? 0,
                    'ratio' =>  $ratio > 100 ? 100 : (int)$ratio
                ];
            }
            unset($v['detail']);
            $v['info'] = $info_val;
            $content[$k] = $v;
        }

        $this->exportExcel($content);
    }

    private function exportExcel($xlsData)
    {

        require_once CMF_ROOT . 'sdk/PHPExcel/PHPExcel.php';

        $fileName = md5("问卷表" . time()) . ".xlsx";
        // //创建新的PHPExcel对象
        $objPHPExcel = new \PHPExcel();
        $objProps = $objPHPExcel->getProperties();


        $objActSheet = $objPHPExcel->getActiveSheet();

        $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);//类型
        $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(20);//问答名称
        $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);//统计信息


        $objPHPExcel->getActiveSheet()->getRowDimension(1)->setRowHeight(30);   // 设置行高
        $objPHPExcel->getActiveSheet()->getRowDimension(2)->setRowHeight(30);   // 设置行高

        $objPHPExcel->setActiveSheetIndex(0) ->setCellValue('A1', '类型');
        $objPHPExcel->setActiveSheetIndex(0) ->setCellValue('B1', '问答名称');
        $objPHPExcel->setActiveSheetIndex(0) ->setCellValue('C1', '统计信息');

        $type = [1=>'单选',2=>'多选',3=>'问答'];

        //exit;
        $column = 2;
        foreach($xlsData as $key => $value){
            $column = $key+2;
            $objPHPExcel->getActiveSheet()->getRowDimension($column)->setRowHeight(80);   // 设置行高
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue('A'.$column,$type[$value['type']]);

            $objPHPExcel->setActiveSheetIndex(0)->setCellValue('B'.$column,$value['title']);

            $info = '';
            if(in_array($value['type'],[1,2])){
                $data = $value['info'];
                foreach ($data as $index=>$item){
                    $option = $item['option'];
                    $count = $item['count'];
                    $ratio = $item['ratio'];
                    $info.= "选择 $option : 完成人数$count , 成百分比$ratio%\r\n";
                }
            }else{
                $data = $value['info'];
                $count = $data['count'];
                $ratio = $data['ratio'];
                $info = "完成人数$count , 成百分比$ratio";
            }


            $objPHPExcel->getActiveSheet()->getStyle('C'.$column)->getAlignment()->setWrapText(true);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue('C'.$column,$info);

        }

        $objActSheet->getColumnDimension('A')->setWidth(20);
        $objActSheet->getColumnDimension('B')->setWidth(20);
        $objActSheet->getColumnDimension('C')->setWidth(150);


        $objPHPExcel->getActiveSheet()->getStyle('A1:P'.$column)->getAlignment()->setHorizontal(\PHPExcel_Style_Alignment::HORIZONTAL_CENTER); //  单元格居中
        $objPHPExcel->getActiveSheet()->getStyle('A1:P'.$column)->getAlignment()->setVertical(\PHPExcel_Style_Alignment::VERTICAL_CENTER); //  垂直居中
        $fileName = iconv("utf-8", "gb2312", $fileName);
        //重命名表
        $objPHPExcel->getActiveSheet()->setTitle('稿件列表');
        //设置活动单指数到第一个表,所以Excel打开这是第一个表
        $objPHPExcel->setActiveSheetIndex(0);
        ob_end_clean();
        ob_start();
        //将输出重定向到一个客户端web浏览器(Excel2007)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header("Content-Disposition: attachment; filename=\"$fileName\"");
        header('Cache-Control: max-age=0');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');

        $objWriter->save('php://output');
        exit;


    }

}