<?php
namespace app\teacher\controller;


use cmf\controller\TeacherBaseController;
use think\Db;

class NotificationController extends  TeacherBaseController{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('cur','notification');
    }

    public function index(){
        $param = $this->request->param();
        $teacher_id = session('teacher.id');
        $Ok_inform_id = array_column(Db::name('class_inform_user')->where(['teacher_uid'=>$teacher_id])->select()->toArray(),'inform_id');
        $where = [
          ['type','<>',1],
            ['teacher_show','=',1],
        ];
        $status = $param['status'] ?? '';
        if($status == 1){
            $where[] = ['id','IN',$Ok_inform_id];
        }elseif($status == 2){
            $where[] = ['id','not IN',$Ok_inform_id];
        }
        $keyword = $param['keyword'] ?? 0;
        if($keyword){
            $where[] = ['title' , 'like' , "%{$keyword}%"];
        }
        $list = Db::name('class_inform')->where($where)->order('id desc')->paginate(20);
        $list->each(function ($v,$k){
            $v['addtime'] =  date('Y-m-d H:i:s',$v['addtime']);
            return $v;
        });
        $this->assign('list',$list);
        $this->assign('Ok_inform_id',$Ok_inform_id);
        $this->assign('page',$list->render());
        return $this->fetch();
    }


    public function detail(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('参数异常');
        }
        $info = Db::name('class_inform')->where(['id'=>$id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        $images = json_decode($info['images'],true);
        foreach ($images as $k=>$v){
            $images[$k] = get_upload_path($v);
        }
        $info['images'] = $images;
        $teacher_id = session('teacher.id');
        $ststus = Db::name('class_inform_user')->where(['inform_id'=>$id,'teacher_uid'=>$teacher_id])->find();
        $this->assign('ststus',$ststus ? 1 : 0);
        $this->assign('info',$info);
        return $this->fetch();
    }

    public function status(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('网络异常');
        }
        $teacher_id = session('teacher.id');

        $exist = Db::name('class_inform_user')->where(['inform_id'=>$id,'teacher_uid'=>$teacher_id])->find();
        if($exist){
            $this->error('已确认收到 无需重复缺');
        }
        $inform_info = Db::name('class_inform')->where('id',$id)->find();
        if(!$inform_info){
            $this->error('数据异常');
        }
        $insert = [
            'addtime'=> time(),
            'teacher_uid' =>$teacher_id,
            'inform_id' => $id
        ];


        $result = Db::name('class_inform_user')->insert($insert);
        if($result === false){
            $this->error('网络异常');
        }

        Db::name('class_teacher')->where(['uid'=>$teacher_id])->setInc('inform_count',-1);
        $http_url = getConfigPri()['http_url'].'/Push/eliminate';
        $param_post = [
            'uid' => json_encode([$teacher_id]),
            'field'=>'clearNotification',
            'type' => '2',
        ];

        curl_post($http_url,$param_post);
        $this->success('成功');
    }
}