<?php
namespace app\teacher\controller;


use cmf\controller\TeacherBaseController;
use think\Db;

class SurveyController extends  TeacherBaseController{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assign('cur','survey');
    }

    public function index(){
        $param = $this->request->param();
        $teacher_id = session('teacher.id');
        $Ok_inform_id = array_column(Db::name('class_survey_user')->where(['teacher_uid'=>$teacher_id])->select()->toArray(),'survey_id');
        $where = [
            ['types','<>',1],
            ['teacher_show','=',1],
        ];
        $status = $param['status'] ?? '';
        if($status == 1){
            $where[] = ['id','IN',$Ok_inform_id];
        }elseif($status == 2){
            $where[] = ['id','not IN',$Ok_inform_id];
        }
        $keyword = $param['keyword'] ?? 0;
        if($keyword){
            $where[] = ['title' , 'like' , "%{$keyword}%"];
        }
        $list = Db::name('class_survey')->where($where)->order('id desc')->paginate(20);
        $list->each(function ($v,$k){
            $v['addtime'] =  date('Y-m-d H:i:s',$v['addtime']);
            $v['end_time'] =  date('Y-m-d H:i:s',$v['end_time']);
            return $v;
        });
        $this->assign('list',$list);
        $this->assign('Ok_inform_id',$Ok_inform_id);
        $this->assign('page',$list->render());
        return $this->fetch();
    }


    public function detail(){
        $id = $this->request->param('id',0,'intval');
        if(!$id){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where(['id'=>$id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        $info['content'] = json_decode($info['content'],true);
        $teacher_id = session('teacher.id');
        $data= Db::name('class_survey_user')->where(['survey_id'=>$id,'teacher_uid'=>$teacher_id])->find();
        $answer = json_decode($data['answer'],true);
        $this->assign('answer',$answer);
        $this->assign('status',$data ? 1 : 0);
        $this->assign('select_list',['A','B','C','D','E','F','G','H','I','J','K','L','M','N']);
        $this->assign('info',$info);
        return $this->fetch();
    }

    public function addpost(){

        $param = $this->request->param();
        $survey_id = $param['survey_id'] ?? '';
        $answer = $param['answer'] ?? [];
        $start_time = $param['start_time'] ?? '';
        $minute = $param['minute'] ?? '';
        if(!$survey_id || !$start_time || !$minute){
            $this->error('参数异常');
        }
        $info = Db::name('class_survey')->where(['id'=>$survey_id])->find();
        if(!$info){
            $this->error('数据异常');
        }
        if($info['end_time'] < time()){
            $this->error('问卷已过期');
        }
        $teacher_id = session('teacher.id');
        $exist = Db::name('class_survey_user')->where(['survey_id'=>$survey_id,'teacher_uid'=>$teacher_id])->find();
        if($exist){
            $this->error('此问卷您已做完');
        }
        $content = json_decode($info['content'],true);
        $count = count($content);
        foreach ($content as $k=>$v){
            $answer_key =isset($answer[$k]) ? array_keys($answer[$k])[0] : $v['type'];
            $answer_value = isset($answer[$k]) ? array_values($answer[$k])[0] : ($answer_key == 3 ? '' : []);
            if(!isset($answer[$k])){
                $answer[$k] = [$answer_key=>$answer_value];
            }
            if(!$answer_key){
                $this->error('信息有误');
            }
            if(!in_array($answer_key,[1,2,3])){
                $this->error('信息有误');
            }
            if($v['type'] != $answer_key){
                $this->error('信息有误');
            }
            if($answer_key == 1){
                if(count($answer_value) > 1){
                    $this->error('单选题只能选择一个');
                }
            }
            $detail = $v['detail'];
            if($v['type'] == 1 || $v['type'] == 2){
                foreach ($answer_value as $key=>$item){
                    $detail[$item] += 1;
                }
            }else{
                if($answer_value){
                    $detail[0] += 1;
                }
            }

            $v['detail'] = $detail;
            $content[$k] = $v;
        }

        $minute = ($minute >= 60) ? ($minute / 60) : 1;
        Db::name('class_survey')->where(['id'=>$info['id']])->update(['content'=>json_encode($content,true),'count'=>$info['count'] + 1]);
        $insert = [
            'survey_id' => $info['id'],
            'uid' => 0,
            'answer' => json_encode($answer,true),
            'addtime' => time(),
            'minute' => $minute,
            'start_time' => $start_time,
            'count' => $count,
            'teacher_uid' =>$teacher_id,
        ];

        Db::name('class_teacher')->where(['uid'=>$teacher_id])->setInc('survey_count',-1);
        Db::name('class_survey_user')->insert($insert);
        $http_url = getConfigPri()['http_url'].'/Push/eliminate';
        $param_post = [
            'uid' => json_encode([$teacher_id]),
            'field'=>'clearSurvey',
            'type' => '2',
        ];
        curl_post($http_url,$param_post);
        $this->success('成功');
    }
}